### ISSUE TITLE
output is almost the same!

### ISSUE THREAD

**Issue by Youlenda** [MrRobot2211/deep-photo-enhance-t2#4]
**Hi,**

**When I run the predict.py, I face this:**
___________
(512, 341)
processing
2021-07-06 05:51:44, [processImg]: file_name = ../input/LPGAN/input/storm.jpg
2021-07-06 05:51:44, [normalizeImage]
2021-07-06 05:51:44, original shape = [341, 512, 3]
2021-07-06 05:52:14, try remove file path = ../input/LPGAN-Result/s.jpg
2021-07-06 05:52:14, remove fail, error = No such file or directory
__________
**And, the output is almost the same as the input image.**
**Would you mind helping me with it? Thank you in advance.**

**Comment by MrRobot2211** [comment]
Hi @Youlenda are you running predict with your own weights or with the pretrained weights?

The other error seems to be related to file paths, what is the organization of your directory?

**Comment by Youlenda** [comment]
Hi @MrRobot2211, I really appreciate your response.

**I want to use an existing model. Actually, I face this error when I run predict.py.**



2021-07-06 16:10:44.671831: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
WARNING:tensorflow:From /content/deep-photo-enhance-t2/DATA.py:10: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
2021-07-06 16:10:45.890988: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-07-06 16:10:45.895474: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-07-06 16:10:45.895521: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: f1e74e307339
2021-07-06 16:10:45.895548: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: f1e74e307339
2021-07-06 16:10:45.895616: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 460.32.3
2021-07-06 16:10:45.895661: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 460.32.3
2021-07-06 16:10:45.895675: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 460.32.3
[]
[]
2021-07-06 16:10:45, exp = 736, load_model path = /content/deep-photo-enhance-t2
2021-07-06 16:10:46.338436: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX512F
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-07-06 16:10:46.351578: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2000189999 Hz
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1375, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,128,128] rhs shape= [1,1,256,128]
	 [[{{node save/Assign_83}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 1304, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 968, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1369, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,128,128] rhs shape= [1,1,256,128]
	 [[node save/Assign_83 (defined at predict.py:48) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_83:
 netG-736_var_scope/netG-736_var_scopeA/netG-736_3/conv_2_w (defined at /content/deep-photo-enhance-t2/CONVNET.py:259)

Original stack trace for 'save/Assign_83':
  File "predict.py", line 48, in <module>
    saver = tf.compat.v1.train.Saver(var_list=netG.weights, max_to_keep=None)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 836, in __init__
    self.build()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 886, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 516, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 358, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 85, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 3565, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "predict.py", line 65, in <module>
    saver.restore(sess, FLAGS['load_model_path_new'])
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 1340, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1,1,128,128] rhs shape= [1,1,256,128]
	 [[node save/Assign_83 (defined at predict.py:48) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_83:
 netG-736_var_scope/netG-736_var_scopeA/netG-736_3/conv_2_w (defined at /content/deep-photo-enhance-t2/CONVNET.py:259)

Original stack trace for 'save/Assign_83':
  File "predict.py", line 48, in <module>
    saver = tf.compat.v1.train.Saver(var_list=netG.weights, max_to_keep=None)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 836, in __init__
    self.build()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 848, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 886, in _build
    build_restore=build_restore)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 516, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 358, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saving/saveable_object_util.py", line 85, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/state_ops.py", line 227, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 60, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 3565, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

**Comment by MrRobot2211** [comment]
It look like your main problem is this 

``` 
2021-07-06 16:10:45.895474: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
```
can you check your tensorflow installation works properly?

**Comment by Youlenda** [comment]
Yes, I think TensorFlow is ok. Now, I have this problem.

Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1,1,128,128] rhs shape= [1,1,256,128]
	 [[node save/Assign_83 (defined at /Users/yalda/Desktop/avir/image_enhancement/deep-photo-enhance-t2/predict_me.py:32) ]]

**Comment by Youlenda** [comment]
Yes, I think TensorFlow is ok. Now, I have this problem.

Unable to open table file /Users/yalda/Desktop/avir/image_enhancement/deep-photo-enhance-t2/LPGAN_exp_G3_736/model: Failed precondition: /Users/yalda/Desktop/avir/image_enhancement/deep-photo-enhance-t2/LPGAN_exp_G3_736/model; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
	 [[node save/RestoreV2 (defined at /Users/yalda/Desktop/avir/image_enhancement/deep-photo-enhance-t2/predict_me.py:32) ]]

For this line:
saver.restore(sess,'/Users/yalda/Desktop/avir/image_enhancement/deep-photo-enhance-t2/LPGAN_exp_G3_736/model')

**Comment by Youlenda** [comment]
Also, when I use the alternative line, I face this error as I mentioned before:

saver.restore(sess, FLAGS['load_model_path_new'])

Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1,1,128,128] rhs shape= [1,1,256,128]
	 [[node save/Assign_83 (defined at /Users/yalda/Desktop/avir/image_enhancement/deep-photo-enhance-t2/predict_me.py:32) ]]

What tf.__version__ I should use?

**Comment by MrRobot2211** [comment]
You should probbly be using tensorflow 2.1, in any case your tensorflow installation is failing to find a cuda device. 
Have you resized your input images before calling predict?

**Comment by Youlenda** [comment]
I'm using TensorFlow '2.5.0'. Actually, I do not yet give any image to the code. I have copied almost all the lines in predict.py, and I am running it. By the way, where should I add the images? In the '/input/LPGAN' file?

**Comment by Youlenda** [comment]
These are the variables: 
https://drive.google.com/file/d/1xAXlQAOBBcoBeYd1EowXQNIubspRBNEc/view?usp=sharing

**Comment by MrRobot2211** [comment]
> I'm using TensorFlow '2.5.0'. Actually, I do not yet give any image to the code. I have copied almost all the lines in predict.py, and I am running it. By the way, where should I add the images? In the '/input/LPGAN' file?

you chould add the imagees in the directories explained in the original repo

**Comment by MrRobot2211** [comment]
If you are not feeding any images to the model this ahoul be probably called something else than outputs are the same. I am closing this if there are no further questions.
